services:
  db:
    image: mysql/mysql-server:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: team3
      MYSQL_DATABASE: march_madness_betting
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3308:3306"
    volumes:
      - ./MySQL_Database:/docker-entrypoint-initdb.d:ro
      - mysql_data:/var/lib/mysql
    container_name: MySQLDatabase

  backend:
    build:
      context: ./backend
    restart: always
    environment:
      FLASK_ENV: development
      FLASK_APP: app.py
      DATABASE_URL: mysql+pymysql://root:team3@db:3306/march_madness_betting
    depends_on:
      - db
    ports:
      - "6000:6000"
    volumes:
      - ./backend:/app
    container_name: FlaskBackend

  frontend:
    build: ./frontend-mm_app
    restart: always
    environment:
      VITE_BACKEND_URL: http://localhost:6000
    depends_on:
      - backend
    ports:
      - "2000:2000"
    volumes:
      - ./frontend-mm_app:/app

volumes:
  mysql_data:
