services:
  - type: web
    name: frontend
    env: docker
    plan: free
    dockerfilePath: ./src/frontend-mm_app/Dockerfile.dev
    dockerContext: ./src/frontend-mm_app
    envVars:
      - key: VITE_BACKEND_URL
        value: https://backend-yr7u.onrender.com

  - type: web
    name: backend
    env: docker
    plan: free
    dockerfilePath: ./src/backend/Dockerfile
    dockerContext: ./src/backend
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SQLALCHEMY_DATABASE_URI
        value: mysql://root:uOhYMhEhZZTyPkLfNefDIhvGXItwAvqB@shortline.proxy.rlwy.net:10082/railway
