services:
  - type: web
    name: frontend
    env: docker
    plan: free
    dockerfilePath: ./src/frontend-mm_app/Dockerfile.dev
    dockerContext: ./src/frontend-mm_app
    envVars:
      - key: VITE_BACKEND_URL
        value: https://backend-yr7u.onrender.com

  - type: web
    name: backend
    env: docker
    plan: free
    dockerfilePath: ./src/backend/Dockerfile
    dockerContext: ./src/backend
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SQLALCHEMY_DATABASE_URI
        value: mysql://root:team3@db:3306/march_madness_betting

  - type: worker
    name: db
    env: docker
    plan: free
    dockerfilePath: ./src/MySQL_Database/Dockerfile
    dockerContext: ./src/MySQL_Database
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: team3
      - key: MYSQL_DATABASE
        value: march_madness_betting
      - key: MYSQL_ROOT_HOST
        value: '%'
