FROM node:18-bullseye

WORKDIR /app

COPY package.json package-lock.json ./

RUN apt-get update && apt-get install -y \
  python3 \
  python3-pip \
  python3-dev \
  make \
  g++ \
  libcairo2-dev \
  libjpeg-dev \
  libpango1.0-dev \
  libgif-dev \
  librsvg2-dev

RUN ln -sf /usr/bin/python3 /usr/bin/python

RUN npm install --legacy-peer-deps

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev","--", "--host", "0.0.0.0"]
